apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: dc2
  namespace: clab-pan-dacom
  labels: {}
  annotations: {}
spec:
  interSwitchLinks:
    linkSelector:
      - eda.nokia.com/role=interSwitch
    poolIPV4: ipv4-pool
    poolIPV6: ''
    vlanID: null
    unnumbered: ''
    qos:
      egressPolicy: ''
      ingressPolicy: ''
  leafs:
    leafNodeSelector:
      - eda.nokia.com/site=dc2,eda.nokia.com/role=leaf
    systemPoolIPV4: ''
    systemPoolIPV6: ''
    asnPool: ''
    routeLeaking:
      exportPolicy: ''
      importPolicy: ''
  overlayProtocol:
    bfd:
      desiredMinTransmitInt: 1000000
      detectionMultiplier: 3
      enabled: true
      minEchoReceiveInterval: 0
      requiredMinReceive: 1000000
    bgp:
      autonomousSystem: 65502
      clusterID: 2.2.2.2
      rrClientNodeSelector:
        - eda.nokia.com/role=leaf
      rrNodeSelector:
        - eda.nokia.com/role=spine
      timers:
        holdTime: 3
        keepAlive: 1
        minimumAdvertisementInterval: 1
        connectRetry: null
      keychain: ''
      exportPolicy: []
      importPolicy: []
      rrIPAddresses: []
    protocol: IBGP
  spines:
    spineNodeSelector:
      - eda.nokia.com/site=dc2,eda.nokia.com/role=spine
    systemPoolIPV4: ''
    systemPoolIPV6: ''
    asnPool: ''
    routeLeaking:
      exportPolicy: ''
      importPolicy: ''
  systemPoolIPV4: systemipv4-pool
  underlayProtocol:
    bfd:
      desiredMinTransmitInt: 100000
      detectionMultiplier: 3
      enabled: true
      minEchoReceiveInterval: 0
      requiredMinReceive: 100000
    bgp:
      asnPool: asn-pool
      timers:
        connectRetry: 10
        holdTime: 3
        keepAlive: 1
        minimumAdvertisementInterval: 1
      keychain: ''
      exportPolicy: []
      importPolicy: []
    protocol:
      - EBGP
  systemPoolIPV6: ''
  fabricSelector: []
  superSpines:
    superSpineNodeSelector: []
    systemPoolIPV4: ''
    systemPoolIPV6: ''
    asnPool: ''
    routeLeaking:
      exportPolicy: ''
      importPolicy: ''
  borderLeafs:
    borderLeafNodeSelector: []
    systemPoolIPV4: ''
    systemPoolIPV6: ''
    asnPool: ''
    routeLeaking:
      exportPolicy: ''
      importPolicy: ''
  routeLeaking:
    exportPolicy: ''
    importPolicy: ''
